Repository mattermost/mattermost-plugin-servicenow, pull requests merged in 2024-04, with the labels that each got.

#170 Created a user-friendly message to display when user authenticates but email does not match
  server/plugin/client.go
Labels: 4: Reviews Complete, Awaiting Submitter Action

#165 Fixed issue #143 and #160
  webapp/package-lock.json
  webapp/package.json
Labels: 3: QA Review

#169 Fixed some issues and enhancement.
  go.mod
  server/constants/constants.go
  server/constants/routes.go
  server/mocks/mock_client.go
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/client.go
  server/plugin/client_test.go
  server/plugin/command.go
  server/serializer/servicenow_event.go
  server/serializer/servicenow_record.go
  server/serializer/subscription.go
  server/testutils/data.go
  webapp/src/containers/addOrEditSubscriptions/subComponents/index.tsx
  webapp/src/containers/addOrEditSubscriptions/subComponents/searchRecordsPanel.tsx
  webapp/src/containers/createIncident/index.tsx
  webapp/src/types/common/payload.d.ts
Labels: 2: Dev Review, 3: QA Review
